AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      Runtime: nodejs8.10
      CodeUri: s3://eva-tutorials/06b8e17533391c489d7f5a9b0677ffbc
      Description: A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /hello/{itemId}
            Method: ANY
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/myHelloTable
  myHelloTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: myHelloTable
      AttributeDefinitions:
      - AttributeName: itemId
        AttributeType: S
      KeySchema:
      - AttributeName: itemId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
